### ISSUE TITLE
I got 'float point exception: core dumped' transforming pics of short cols.

### ISSUE THREAD

**Issue by Cancerce1l** [Canjie-Luo/Text-Image-Augmentation#1]

**Comment by Canjie-Luo** [comment]
Can you provide me more details? @Cancerce1l

**Comment by Canjie-Luo** [comment]
Setting the width to 12 still works.  If you want to further decrease the width, please use `Augment.GenerateDistort(im, 2)` instead of `Augment.GenerateDistort(im, 4)`. But I recommend larger size of images. You may have better transform results. @Cancerce1l
