### ISSUE TITLE
About the agent updating and initialization

### ISSUE THREAD

**Issue by PkuDavidGuan** [Canjie-Luo/Text-Image-Augmentation#13]
I have two questions about the nice paper "Learn to Augment: Joint Data Augmentation and Network Optimization
for Text Recognition":

    1.  In LIne 9 of the Algorithm 1, why the Agent network update towards -S'? I don't understand why -S' is a harder moving state.
    2. As for the agent initialization, what is the initialization direction of the 2*(N+1) fiducial points?

**Comment by Canjie-Luo** [comment]
1. Note that for the modified point, S == -S'. The S' decrease the difficulty, so we use S (-S') to update the agent.
![image](https://user-images.githubusercontent.com/32130508/156693203-eadd9176-e109-4287-b86e-33fa7865d58c.png)
2. The direction is randomly initialized.
