### ISSUE TITLE
CMake fail

### ISSUE THREAD

**Issue by huizhang0110** [Canjie-Luo/Text-Image-Augmentation#2]
Thanks for your code, but when I compiled the code according to the readme.md, I meet the following error.

Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)

![default](https://user-images.githubusercontent.com/32508847/50905887-cbc9eb80-145e-11e9-9688-6748cfab1d0f.JPG)

**Comment by Canjie-Luo** [comment]
Please reinstall your Python2.7 or try:
 `cmake -D PYTHON_INCLUDE_DIR=/usr/include/python2.7 -D PYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so -D CUDA_USE_STATIC_CUDA_RUNTIME=OFF ..` @huizhang0110

**Comment by huizhang0110** [comment]
Thanks, I successfully compiled  `Augment.so` through 
```
/home/zhui/.local/cmake3.13/bin/cmake .. -D CUDA_USE_STATIC_CUDA_RUNTIME=OFF \                                                                                                                    1 ↵
-DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")  \
-DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
```
But how do I call it via python (import Augment)  like in demo.py ? @Canjie-Luo

**Comment by Canjie-Luo** [comment]
Copy the `Augment.so` to the target folder or your system library folder (/usr/lib/ and so on) and `import Augment`.

**Comment by huizhang0110** [comment]
There is still a problem in my anaconda3 environment. Do you have a plan to support python3 env?

**Comment by Canjie-Luo** [comment]
Of course. That's our future work. But it may take some time. Welcome to develop the project together. You can create a new branch and the current stable version remains as the master.
