### ISSUE TITLE
floating point exception (core dumped) when process images with different size

### ISSUE THREAD

**Issue by cuhk-hbsun** [Canjie-Luo/Text-Image-Augmentation#3]
If I resize all the images to the same size before transforming, there will be no error.
By the way, all the images with height = 70 and width in (200, 400) , no very small size.

**Comment by Canjie-Luo** [comment]
Can you give me more details? Do you use my tool in PyTorch?

**Comment by cuhk-hbsun** [comment]
I double checked my scripts and found that there is one file which is not an image. 
I remove that file then the code worked without error.
Sorry to bother you and thank you very much!

**Comment by Canjie-Luo** [comment]
That's all right. Hopefully the tool can help you.
