### ISSUE TITLE
i got some trouble in 'make'

### ISSUE THREAD

**Issue by Jinwanqi** [Canjie-Luo/Text-Image-Augmentation#4]
[ 12%] Building CXX object CMakeFiles/Augment.dir/src/conversion.cpp.o
In file included from /home/fbas/下载/Scene-Text-Image-Transformer-master/src/conversion.cpp:1:0:
/home/fbas/下载/Scene-Text-Image-Transformer-master/include/conversion.h:8:33: fatal error: numpy/ndarrayobject.h: 没有那个文件或目录
compilation terminated.
CMakeFiles/Augment.dir/build.make:62: recipe for target 'CMakeFiles/Augment.dir/src/conversion.cpp.o' failed
make[2]: *** [CMakeFiles/Augment.dir/src/conversion.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Augment.dir/all' failed
make[1]: *** [CMakeFiles/Augment.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by keeofkoo** [comment]
@Jinwanqi It seems that `make` doesn't find numpy's headers. Appending the include directory to `CPLUS_INCLUDE_PATH` should fix this. Mine's located at `/usr/local/lib/python2.7/site-packages/numpy/core/include`, i.e. run
```python
CPLUS_INCLUDE_PATH="${CPLUS_INCLUDE_PATH}:/usr/local/lib/python2.7/site-packages/numpy/core/include" make
```

Good luck with that.

**Comment by Canjie-Luo** [comment]
@keeofkoo Thanks for your reply. 
@Jinwanqi Sorry for late reply. The simplest way is to copy the numpy include folder  to `./include`. Hopefully it can help you.

**Comment by Jinwanqi** [comment]
> @Jinwanqi It seems that `make` doesn't find numpy's headers. Appending the include directory to `CPLUS_INCLUDE_PATH` should fix this. Mine's located at `/usr/local/lib/python2.7/site-packages/numpy/core/include`, i.e. run
> 
> ```python
> CPLUS_INCLUDE_PATH="${CPLUS_INCLUDE_PATH}:/usr/local/lib/python2.7/site-packages/numpy/core/include" make
> ```
> 
> Good luck with that.

thank you!
but i meet another problem:
when i use opencv3.4.2, error comes as :
/home/jin/下载/Scene-Text-Image-Transformer-master/include/delaunay.h:11:37: fatal error: opencv2/legacy/legacy.hpp: 没有那个文件或目录
compilation terminated.
CMakeFiles/Augment.dir/build.make:62: recipe for target 'CMakeFiles/Augment.dir/src/delaunay.cpp.o' failed
make[2]: *** [CMakeFiles/Augment.dir/src/delaunay.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Augment.dir/all' failed
make[1]: *** [CMakeFiles/Augment.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
 
this is because cv3 quit the legacy module;
but when i change to cv2. problem comes when cmake,like
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106501
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:13 (find_package)


-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   python
CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/jin/下载/Scene-Text-Image-Transformer-master/build/CMakeFiles/CMakeOutput.log".
Makefile:356: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1


i use conda to install opencv,shall i install it with source code?

**Comment by keeofkoo** [comment]
@Jinwanqi Looks like it didn't find the proper config to handle the OpenCV2 library. Anaconda doesn't seem to offer an installation of version 2, you could build it from source.
